<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:atom="http://www.w3.org/2005/Atom">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html>
      <head>
        <title><xsl:value-of select="/rss/channel/title"/></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <style type="text/css">
          /* 极简/学术风格 */
          body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; /* 清晰的无衬线字体 */
            line-height: 1.7;
            margin: 0 auto;
            max-width: 720px; /* 适中宽度 */
            padding: 3em 1.5em;
            background-color: #fdfdfd; /* 非常浅的灰色背景 */
            color: #333; /* 深灰色文字 */
            font-size: 16px; /* 标准字体大小 */
          }

          /* 标题样式 */
          h1 {
            font-size: 1.75em; /* 相对小一点的标题 */
            margin-bottom: 1em;
            border-bottom: 1px solid #eee; /* 非常浅的边框 */
            padding-bottom: 0.4em;
            font-weight: 500; /* Medium weight */
            color: #111; /* 黑色标题 */
          }
          h1 a {
            color: inherit;
            text-decoration: none;
          }
          h1 a:hover {
             text-decoration: underline; /* 悬停下划线 */
          }

          /* 描述文字 */
          p {
            margin: 0.5em 0 2.5em 0;
            color: #555; /* 中灰色 */
            font-size: 1em;
          }

          /* 列表样式 */
          ul {
            list-style: none;
            padding: 0;
          }

          /* 列表项样式 - 移除边框和阴影，增加间距 */
          li {
            background-color: transparent; /* 透明背景 */
            border: none; /* 无边框 */
            border-radius: 0; /* 无圆角 */
            margin-bottom: 2em; /* 增加列表项间距 */
            padding: 0; /* 无内边距 */
            box-shadow: none; /* 无阴影 */
            border-bottom: 1px dotted #ddd; /* 用虚线分隔 */
            padding-bottom: 1.5em; /* 虚线下方的间距 */
          }
          li:last-child {
             border-bottom: none; /* 最后一项无分隔线 */
             padding-bottom: 0;
             margin-bottom: 0;
          }
          li:hover {
             /* 无悬停效果，保持简洁 */
          }


          /* 列表项标题 */
          li h2 {
            margin: 0 0 0.3em 0;
            font-size: 1.15em; /* 稍大一点 */
            font-weight: 500; /* Medium weight */
          }
          li h2 a {
            color: #0056b3; /* 蓝色链接 */
            text-decoration: none;
            transition: color 0.2s ease-in-out;
          }
          li h2 a:hover {
            color: #003d80; /* 深蓝色悬停 */
            text-decoration: underline;
          }

          /* 发布日期样式 */
          .pubDate {
            color: #777; /* 灰色日期 */
            font-size: 0.875em; /* text-sm */
            margin-bottom: 0.5em;
            display: block;
          }

          /* 描述内容样式 */
          .description {
            color: #444; /* 稍深的灰色 */
            font-size: 0.95em;
          }

          /* 页脚样式 */
          footer {
            margin-top: 4em;
            padding-top: 1em;
            border-top: 1px solid #eee; /* 非常浅的边框 */
            font-size: 0.875em; /* text-sm */
            color: #888; /* 浅灰色页脚 */
            text-align: center;
            line-height: 1.5; /* 增加行高以便容纳多行 */
          }
        </style>
      </head>
      <body>
        <h1><a href="{/rss/channel/link}" target="_blank"><xsl:value-of select="/rss/channel/title"/></a></h1>
        <p><xsl:value-of select="/rss/channel/description"/></p>
        <ul>
          <xsl:for-each select="/rss/channel/item">
            <li>
              <h2><a href="{link}" target="_blank"><xsl:value-of select="title"/></a></h2>
              <div class="pubDate">
                <xsl:value-of select="pubDate"/>
              </div>
              <div class="description">
                <xsl:value-of select="description"/>
              </div>
            </li>
          </xsl:for-each>
        </ul>
        <footer>
          Generated by Astro using @astrojs/rss <br /> 
          Powered by <a href="https://github.com/Dnzzk2/Litos" target="_blank" style="color: #0056b3; text-decoration: none;">Litos Theme</a>
        </footer>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>